import { CropConfig, ShipConfig, StageData } from '../types/game';

export const CROPS: Record<string, CropConfig> = {
  WHEAT: {
    id: 'WHEAT',
    name: 'Lúa Sao (Star Wheat)',
    description: 'Cây lương thực vũ trụ cơ bản, tăng trưởng nhanh.',
    growTimeSeconds: 15, // Nhanh để trải nghiệm chơi thử ngay
    seedCost: 5,
    baseSellPrice: 15,
    harvestYield: 2,
    icon: '🌾',
  },
  ENERGY_CORN: {
    id: 'ENERGY_CORN',
    name: 'Bắp Năng Lượng (Energy Corn)',
    description: 'Chứa năng lượng sinh học cao, dùng để chế tạo nhiên liệu.',
    growTimeSeconds: 40,
    seedCost: 20,
    baseSellPrice: 60,
    harvestYield: 2,
    icon: '🌽',
  },
  NANO_TOMATO: {
    id: 'NANO_TOMATO',
    name: 'Cà Chua Nano (Nano Tomato)',
    description: 'Thành phần tổng hợp hạt phân tử sinh học hồi máu.',
    growTimeSeconds: 90,
    seedCost: 50,
    baseSellPrice: 160,
    harvestYield: 3,
    icon: '🍅',
  },
  CRYSTAL_BERRY: {
    id: 'CRYSTAL_BERRY',
    name: 'Dâu Pha Lê (Crystal Berry)',
    description: 'Quả quý hiếm kết tinh từ bức xạ tinh vân.',
    growTimeSeconds: 180,
    seedCost: 150,
    baseSellPrice: 500,
    harvestYield: 2,
    icon: '🍇',
  },
};

export const SHIPS: Record<string, ShipConfig> = {
  SHIP_SCOUT_01: {
    id: 'SHIP_SCOUT_01',
    name: 'Scout-01 Trinh Sát',
    rarity: 'N',
    shipClass: 'FIGHTER',
    description: 'Chiến cơ tiêu chuẩn của liên minh ngân hà.',
    baseStats: {
      hp: 1200,
      shield: 600,
      attack: 180,
      defense: 60,
      critRate: 0.05,
      speed: 320,
    },
    passiveName: 'Cơ Động Cơ Bản',
    passiveDesc: 'Tăng 5% tốc độ bay.',
    spriteKey: 'ship_scout',
    bulletType: 'PLASMA',
  },
  SHIP_GUARDIAN_01: {
    id: 'SHIP_GUARDIAN_01',
    name: 'Guardian-01 Hộ Vệ',
    rarity: 'R',
    shipClass: 'TANK',
    description: 'Trang bị giáp từ trường kiên cố chống chịu đạn pháo.',
    baseStats: {
      hp: 2500,
      shield: 1600,
      attack: 220,
      defense: 180,
      critRate: 0.03,
      speed: 260,
    },
    passiveName: 'Tấm Chắn Từ Tính',
    passiveDesc: 'Tự động hồi 30 Khiên mỗi giây.',
    spriteKey: 'ship_guardian',
    bulletType: 'SPREAD',
  },
  SHIP_FALCON_X: {
    id: 'SHIP_FALCON_X',
    name: 'Falcon-X Chim Ưng Sấm',
    rarity: 'SR',
    shipClass: 'FIGHTER',
    description: 'Tốc độ cực nhanh, trang bị tia plasma kép áp đảo.',
    baseStats: {
      hp: 3800,
      shield: 2200,
      attack: 540,
      defense: 150,
      critRate: 0.12,
      speed: 380,
    },
    passiveName: 'Tia Chớp Bão Táp',
    passiveDesc: 'Mỗi phát bắn có 15% cơ hội kích hoạt tia sét lan tỏa.',
    spriteKey: 'ship_falcon',
    bulletType: 'LASER',
  },
  SHIP_NOVA_HUNTER: {
    id: 'SHIP_NOVA_HUNTER',
    name: 'Nova Hunter Kẻ Săn Sao',
    rarity: 'SSR',
    shipClass: 'SNIPER',
    description: 'Chiến cơ tối thượng trang bị pháo hạt tử hủy diệt Boss.',
    baseStats: {
      hp: 7500,
      shield: 4200,
      attack: 1250,
      defense: 320,
      critRate: 0.22,
      speed: 350,
    },
    passiveName: 'Diệt Thần Vực Thẳm',
    passiveDesc: '+40% Sát thương lên Boss & Quái Tinh Anh.',
    spriteKey: 'ship_nova',
    bulletType: 'MISSILE',
  },
};

export const STAGES: StageData[] = [
  {
    id: 'STAGE_1_1',
    chapter: 1,
    stageNumber: 1,
    name: '1-1: Ngoại Vi Gaia',
    energyCost: 5,
    recommendedPower: 300,
    enemyWaves: 4,
    bossName: 'Drone Chỉ Huy Alpha',
    bossHp: 3000,
    rewards: {
      creditsMin: 80,
      creditsMax: 150,
      exp: 50,
      materials: [
        { itemId: 'IRON', chance: 0.9, amount: 5 },
        { itemId: 'TITANIUM', chance: 0.3, amount: 2 },
      ],
    },
  },
  {
    id: 'STAGE_1_2',
    chapter: 1,
    stageNumber: 2,
    name: '1-2: Vành Đai Mảnh Vỡ',
    energyCost: 5,
    recommendedPower: 600,
    enemyWaves: 5,
    bossName: 'Cơ Giáp Tinh Vân Beta',
    bossHp: 7500,
    rewards: {
      creditsMin: 180,
      creditsMax: 300,
      exp: 120,
      materials: [
        { itemId: 'IRON', chance: 1.0, amount: 10 },
        { itemId: 'TITANIUM', chance: 0.6, amount: 5 },
        { itemId: 'BLUEPRINT_NOVA_HUNTER', chance: 0.15, amount: 1 },
      ],
    },
  },
];
